//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAKittenApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitten
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitten()
        {
            this.Rents = new HashSet<Rent>();
        }
    
        public int KittenID { get; set; }
        public string KittenName { get; set; }
        public string KittenColor { get; set; }
        public string FurLength { get; set; }
        public string Personality { get; set; }
        public string KittyImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent> Rents { get; set; }
    }
}
