//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAKittenApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int RentalID { get; set; }
        public System.DateTime RentalDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public int CustomerID { get; set; }
        public int KittenID { get; set; }
        public int RatingID { get; set; }
        public int RentalDetailID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Kitten Kitten { get; set; }
        public virtual Rating Rating { get; set; }
        public virtual RentalDetail RentalDetail { get; set; }
    }
}
