//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAKittenApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RentalDetail()
        {
            this.Rents = new HashSet<Rent>();
        }
    
        public int RentalDetailID { get; set; }
        public decimal PricePerHour { get; set; }
        public Nullable<decimal> Discounts { get; set; }
        public Nullable<decimal> Adders { get; set; }
        public decimal TotalCharged { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent> Rents { get; set; }
    }
}
